name: app_tesi_unibo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0-152.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_spinkit: 5.1.0
  health: ^13.1.3
  permission_handler: ^11.3.1
  shared_preferences: ^2.2.3
  cryptography: ^2.7.0
  flutter_secure_storage: ^9.2.2
  dio: ^5.7.0
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
